name: network_manager
description: A simple Dart package to check internet connection.
version: 1.0.0
environment:
  sdk: ">=2.14.4 <3.0.0"

dependencies:
  internet_connection_checker: ^0.0.1+3

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
